name: hashicorp/vault-ruby/run-tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # https://endoflife.date/ruby
        ruby: ["3.1", "3.2", "3.3", "3.4"]
        vault: ["1.14.10", "1.15.6", "1.16.3", "1.17.6", "1.18.4"]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ruby/setup-ruby@32110d4e311bd8996b2a82bf2a43b714ccc91777 # v1.221.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: "Install vault cli"
        run: |
          curl -sLo vault.zip "https://releases.hashicorp.com/vault/${{ matrix.vault }}/vault_${{ matrix.vault }}_linux_amd64.zip"
          unzip vault.zip
          mkdir -p "$HOME/bin"
          mv vault "$HOME/bin"
          echo "$HOME/bin" >> "$GITHUB_PATH"
      - run: bundle exec rake

permissions:
  contents: read
